---

# TODO: a more comprehensive check, not just $ACTIVEMQ_CONF, fail otherwise
- stat: path="{{ activemq_base }}/conf"
  register: conf_base

- name: Install Apache ActiveMQ
  include_tasks: install.yml
  when: not conf_base.stat.exists

# Update ActiveMQ configuration
- name: Update common ActiveMQ configuration
  copy:
    src: "{{ item }}"
    dest: "{{ activemq_base }}/conf"
    owner: "{{ activemq_user }}"
    group: "{{ activemq_group }}"
    mode: 0644
  with_fileglob:
    - "activemq/*"

- name: Update per host ActiveMQ configuration
  copy:
    src: "{{ item }}"
    dest: "{{ activemq_base }}/conf"
    owner: "{{ activemq_user }}"
    group: "{{ activemq_group }}"
    mode: 0644
  with_fileglob:
    - "{{ inventory_hostname }}/activemq/*"

- name: Reload systemd service
  systemd:
    daemon-reload: yes
    enabled: yes
    state: started
    name: activemq
  when: activemq_create_service
